on:
  push:
    tags:
      - "v*.*.*"

name: Release Template File

jobs:
  build:
    name: Release Template File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install Python3
        run: sudo apt -y install python3

      - name: Build Latex file
        run: python3 maker_latex.py Y

      - name: Download font
        run: |
          wget -q -O source-code-pro.zip https://github.com/adobe-fonts/source-code-pro/releases/download/2.030R-ro%2F1.050R-it/source-code-pro-2.030R-ro-1.050R-it.zip
          wget -q -O source-han-serif.zip https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/09_SourceHanSerifSC.zip
          wget -q -O source-han-sans.zip https://github.com/adobe-fonts/source-han-sans/releases/download/2.004R/SourceHanSansCN.zip
          unzip -q source-code-pro.zip -d source-code-pro
          unzip -q source-han-serif.zip -d source-han-serif
          unzip -q source-han-sans.zip -d source-han-sans
          mkdir -p ./.fonts
          cp -v source-code-pro/*/OTF/*.otf ./.fonts/
          cp -v source-han-serif/OTF/*/*.otf ./.fonts/
          cp -v source-han-sans/SubsetOTF/*/*.otf ./.fonts/
          rm -rf source-code-pro{,.zip} source-han-serif{,.zip} source-han-sans{,.zip}

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: ACM-Template.tex
          latexmk_use_xelatex: true
          working_directory: .
          args: "-g -pdf -file-line-error -halt-on-error -interaction=nonstopmode"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ACM-Template.pdf