on:
  push:
    tags:
      - "v*.*.*"

name: Release Template File

jobs:
  build:
    name: Release Template File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update APT
        run: sudo apt update

      - name: Install Python3
        run: sudo apt -y install python3

      - name: Build Latex file
        run: python3 maker_latex.py Y

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: ACM-Template.tex
          latexmk_use_xelatex: true
          pre_compile: |
            wget -q -O notosans.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip"
            wget -q -O notoserif.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-hinted.zip"
            wget -q -O notoserifcjk.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKsc-hinted.zip"
            wget -q -O notosanscjk.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip"
            wget -q -O robotomono.zip "https://fonts.google.com/download?family=Roboto%20Mono"
            unzip -q notosans.zip -d notosans
            unzip -q notoserif.zip -d notoserif
            unzip -q notosanscjk.zip -d notosanscjk
            unzip -q notoserifcjk.zip -d notoserifcjk
            unzip -q robotomono.zip -d robotomono
            cp -r notosans notoserif notosanscjk notoserifcjk robotomono /usr/share/fonts
            fc-cache

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ACM-Template.pdf